### ISSUE TITLE
alors... les gars... comment vous expliquer qu'il manque des champs à l'inscription...

### ISSUE THREAD

**Issue by wilfriite** [Erwan8989/mspr-plantes-vertes#6]

**Comment by DevDeNiro** [comment]
Petite erreur de conception, le maquettiste n'a pas terminé son travail…

**Comment by wilfriite** [comment]
OK trql, on a encore du temps

**Comment by wilfriite** [comment]
Mon envie de vous harceler par issues github grandit de seconde en seconde
